name: backoffice52switch
description: "web/ios/android based backoffice application for 52switch."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  graphql_flutter: ^5.0.1
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  http: ^0.13.6
  intl: ^0.19.0
  firebase_auth: ^5.3.2
  logger: ^1.4.0
  firebase_core: ^3.7.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:

  uses-material-design: true
