// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyuOukmIzjhHkpiEpAYTv_XigTv3l6yiw',
    appId: '1:620949033231:web:9187aba5cf05dc80f6ae7a',
    messagingSenderId: '620949033231',
    projectId: 'switch-cf287',
    authDomain: 'switch-cf287.firebaseapp.com',
    storageBucket: 'switch-cf287.firebasestorage.app',
    measurementId: 'G-G29PR02FT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVIuPR_p1q_jS1zZmo9HpOCJWiyOraogg',
    appId: '1:620949033231:android:792f22ce07732b4ef6ae7a',
    messagingSenderId: '620949033231',
    projectId: 'switch-cf287',
    storageBucket: 'switch-cf287.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLWrmgE7qca84bEqgHU3tr_dsYbkK60CE',
    appId: '1:620949033231:ios:efc88636a1104395f6ae7a',
    messagingSenderId: '620949033231',
    projectId: 'switch-cf287',
    storageBucket: 'switch-cf287.firebasestorage.app',
    iosBundleId: 'com.example.backoffice52switch',
  );
}
